# Generated by Django 4.0.1 on 2022-01-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_kstest_delete_test'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kstest',
            table='ks_intern_data',
        ),
    ]
