# Generated by Django 4.0.1 on 2022-01-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_kstest_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kstest',
            table='posts_kstest',
        ),
    ]
