# Generated by Django 4.0.1 on 2022-01-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_kstest_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kstest',
            old_name='ks_ID',
            new_name='ks_id',
        ),
        migrations.RenameField(
            model_name='kstest',
            old_name='ks_Name',
            new_name='ks_name',
        ),
    ]
