# Generated by Django 4.0.1 on 2022-01-23 11:02

from django.db import migrations, models
import multiprocessing.sharedctypes


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_ks_id_kstest_ks_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kstest',
            name='ks_temperature',
            field=models.IntegerField(),
        ),
    ]
