# Generated by Django 4.0.1 on 2022-01-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_kstest_ks_temperature'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kstest',
            table=None,
        ),
    ]
