# Generated by Django 4.0.1 on 2022-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_kstest_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kstest',
            name='ks_time',
            field=models.DateTimeField( max_length=6),
        ),
    ]
