# Generated by Django 4.0.1 on 2022-01-23 13:14

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_kstest_ks_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kstest',
            name='ks_time',
            field=models.DateTimeField( max_length=6),
        ),
    ]
