# Generated by Django 4.0.1 on 2022-01-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_kstest_ks_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kstest',
            name='ks_name',
        ),
        migrations.RemoveField(
            model_name='kstest',
            name='ks_time',
        ),
    ]
