# Generated by Django 4.0.1 on 2022-01-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_kstest_ks_name_remove_kstest_ks_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kstest',
            old_name='ks_id',
            new_name='id',
        ),
        migrations.AlterModelTable(
            name='kstest',
            table=None,
        ),
    ]
