# Generated by Django 4.0.1 on 2022-01-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_rename_ks_id_kstest_id_alter_kstest_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kstest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='kstest',
            table='posts_kstest',
        ),
    ]
