# Generated by Django 4.0.1 on 2022-01-23 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_kstest_id_alter_kstest_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kstest',
            old_name='id',
            new_name='ks_id',
        ),
        migrations.AddField(
            model_name='kstest',
            name='ks_name',
            field=models.CharField(default='Yu', max_length=20),
        ),
        migrations.AddField(
            model_name='kstest',
            name='ks_time',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=6),
        ),
    ]
