# Generated by Django 4.0.1 on 2022-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_rename_id_kstest_ks_id_kstest_ks_name_kstest_ks_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kstest',
            name='ks_name',
            field=models.CharField(default='請輸入名字', max_length=20),
        ),
    ]
